version: '3.4'

services:
  react-development:
    image: react-development
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
